//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int aid { get; set; }
        public Nullable<int> cRef { get; set; }
        public string rNum { get; set; }
        public Nullable<decimal> restBill { get; set; }
        public Nullable<decimal> roomBill { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
