//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.FoodBills = new HashSet<FoodBill>();
        }
    
        public int refno { get; set; }
        public string cname { get; set; }
        public string gender { get; set; }
        public string addrs { get; set; }
        public string postcode { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string nationality { get; set; }
        public string idtype { get; set; }
        public string idnum { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public string roomnum { get; set; }
        public Nullable<int> numdays { get; set; }
        public Nullable<decimal> totalrent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodBill> FoodBills { get; set; }
    }
}
