//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodBill
    {
        public int bid { get; set; }
        public Nullable<int> cRef { get; set; }
        public string RNum { get; set; }
        public Nullable<System.DateTime> dateOfBill { get; set; }
        public Nullable<decimal> amount { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
