//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string roomNum { get; set; }
        public string roomtype { get; set; }
        public Nullable<int> floornum { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> roomstatus { get; set; }
    }
}
